# Generated by Django 6.0.1 on 2026-03-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture.",
                null=True,
                upload_to="avatars/",
                verbose_name="avatar",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                db_index=True,
                default="1773176117697717",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                verbose_name="username",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="idx_user_email"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["username"], name="idx_user_username"),
        ),
    ]
