# Generated by Django 6.0.1 on 2026-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_avatar_customuser_username_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customuser",
            name="idx_user_email",
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="idx_user_username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
